version: "3"
services:
  area_mobile:
    build: './'
    volumes:
      - ./apk:/mobile_apk/
    command: sh -c 'flutter build apk && cp build/app/outputs/apk/release/app-release.apk /mobile_apk/client.apk'
