version: "3"
services:
  server:
    image: node:16.14-alpine3.14
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app/server
    command: sh -c "cd /app/server && npm install && npm run ${MODE}"
